### ISSUE TITLE
Commands used for deployment

### ISSUE THREAD

**Issue by mrudulfingent** [rraj-gautam/k8s-jibri#2]
Thanks very much for the information you shared. I am a newbie to kubernetes and got some idea about deployment of Jibri using the files you provided. Can you please share the command that you used for the stateful deployment ? Thanks in advance.

**Comment by rraj-gautam** [comment]
Hello @mrudulfingent The command to deploy statefulset is : 
`kubetctl apply -f statefulset.yml`

You can see the documentation on deployments at [kuberentes official documentation]( https://kubernetes.io/docs/concepts/workloads/controllers/deployment/)

**Comment by mrudulfingent** [comment]
> Hello @mrudulfingent The command to deploy statefulset is :
> `kubetctl apply -f statefulset.yml`
> 
> You can see the documentation on deployments at [kuberentes official documentation](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/)

Thank you :)
