### ISSUE TITLE
Pods can't connect to internet 

### ISSUE THREAD

**Issue by mrudulfingent** [rraj-gautam/k8s-jibri#3]
I met with an issue that pods could not connect to internet. 
In the logs I got:

_**org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: 'meet1.test.com:5222' failed because: meet1.test.com/192.168.39.24 exception: java.net.SocketTimeoutException: connect timed out_**

This is happening when jibri tries to connect with jitsi server.  I tried with both private and public IPs of Jitsi server. But no luck!

Also I entered into pod's shell and tried 'apt update' . But its also not working as it can't connect to internet.
I used the dnsConfig.yaml exactly the same as provided in this link. I don't know whether that values are correct for my use case.

Any suggestions are welcome. Thanks in advance. :)

**Comment by rraj-gautam** [comment]
Are you able to connect to internet from Nodes itself? 
FYI, you can change the nameserver values according to your network.

**Comment by mrudulfingent** [comment]
yes. From nodes I can connect.

**Comment by itsmaniche18** [comment]
@mrudulfingent Is there an internet connection in your host?

**Comment by mrudulfingent** [comment]
> @mrudulfingent Is there an internet connection in your host?

yes. The internet connection in the machines and network is fine.
I did enter into pod shell and tried to run "apt update" . It shows as:

"Err:1 http://deb.debian.org/debian stretch InRelease                 
  Temporary failure resolving 'deb.debian.org ".

The same thing happens when I tried it on container shell.

**Comment by itsmaniche18** [comment]
Add me on skype --> itsmaniche18 so that we can screenshare 

Thanks

**Comment by mrudulfingent** [comment]
> Add me on skype --> itsmaniche18 so that we can screenshare
> 
> Thanks

Okay .. Thank you

**Comment by rraj-gautam** [comment]
Please use updated code to solve the issue
