### ISSUE TITLE
Machine type for this k8s

### ISSUE THREAD

**Issue by marcoadasilvaa** [rraj-gautam/k8s-jibri#4]
Thank you very much for the contribution.

what are the specifications of the node? 8CPU and 32 GB Ram?

You are testing concurrence for 100 conferences simultaneous?

**Comment by itsmaniche18** [comment]
1 Jibri needs 2 core and 1 GB of ram.
You can use t3.medium for master and c5.2xlarge for nodes in which you can host 5 jibris in 1 node.
